[dev_esp32_c3]
extends         = base
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
;monitor_speed   = 115200
upload_speed    = 1000000
build_flags     = ${base.build_flags}
lib_deps        = ${base.lib_deps}
                  ${base.network_deps}
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip

[dev_esp32_c6]
extends         = base
board           = esp32-c6-devkitm-1
board_build.mcu = esp32c6
board_build.f_cpu = 160000000L
;monitor_speed   = 115200
upload_speed    = 1000000
build_flags     = ${base.build_flags}
lib_deps        = ${base.lib_deps}
                  ${base.network_deps}
board_build.sdkconfig = sdkconfig.defaults
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip


[env:kitch]
board_build.partitions = config/partitions_custom-a3.csv
extends         = dev_esp32_c6
build_flags     = ${dev_esp32_c6.build_flags}
                  -DARDUINO_USB_CDC_ON_BOOT=1
                  -DARDUINO_USB_MODE=1
                  -DCORE_DEBUG_LEVEL=3
build_src_flags = ${project_demo.build_src_flags}
                  ${feature_wifi.build_src_flags}
                  ${feature_ota.build_src_flags}
                  -DMAX_BUFFERS=50
                  -fno-omit-frame-pointer
                  -DONBOARD_PIXEL_POWER=8
                  -DONBOARD_PIXEL_DATA=8
                  -DONBOARD_PIXEL_SCALE_BRIGHTNESS=8 # 1/32 brightness
                  -DONBOARD_PIXEL_ORDER=EOrder::RBG
                  -DCOLOR_ORDER=EOrder::RGB # Strip trait
                  -DPROJECT_NAME="\"Roberts Kitchen\""
                  -DTIME_BEFORE_LOCAL=30
                  -DDEFAULT_EFFECT_INTERVAL=60*60*24*5
                  -DMATRIX_WIDTH=100
                  -DLED_PIN0=14
                  -DDHT11_PIN=7
                  ${dev_esp32_c6.build_src_flags}
