[dev_esp32_c3]
extends         = base
board           = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
;monitor_speed   = 115200
upload_speed    = 1000000
build_flags     = ${base.build_flags}
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[dev_esp32_c6]
extends         = base
board           = esp32-c6-devkitm-1
board_build.mcu = esp32c6
board_build.f_cpu = 160000000L
;monitor_speed   = 115200
upload_speed    = 1000000
build_flags     = ${base.build_flags}
board_build.sdkconfig = sdkconfig.defaults
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip


[env:kitch]
board_build.partitions = config/partitions_custom-a3.csv
extends         = dev_esp32_c6
build_src_flags = 
                  -DMAX_BUFFERS=50
                  -fno-omit-frame-pointer
                  ${dev_esp32_c6.build_src_flags}

build_flags    = -DDEMO=1
                  # -DEFFECTS_MINIMAL=1
                  -DEFFECTS_DEMO=1
#  -DPOWER_LIMIT_MW=2500
  -DONBOARD_PIXEL_POWER=8
  -DONBOARD_PIXEL_DATA=8
  -DONBOARD_PIXEL_SCALE_BRIGHTNESS=8 # 1/32 brightness
  -DONBOARD_PIXEL_ORDER=EOrder::RBG
     -DCOLOR_ORDER=EOrder::RGB # Strip trait 
                  -DPROJECT_NAME="\"Roberts Kitchen\""
                  -DENABLE_AUDIOSERIAL=0
                  -DENABLE_WIFI=1
                  -DINCOMING_WIFI_ENABLED=1
                  -DWAIT_FOR_WIFI=0
                  -DTIME_BEFORE_LOCAL=30
                  -DENABLE_WEBSERVER=1
                  -DENABLE_NTP=1
                  -DENABLE_OTA=1
                  -DENABLE_REMOTE=0
                  -DENABLE_AUDIO=0
                  -DENABLE_REMOTEDEBUG=0
                  -DARDUINO_USB_CDC_ON_BOOT=1
                  -DARDUINO_USB_MODE=1
                  -DCORE_DEBUG_LEVEL=3
                  -DDEFAULT_EFFECT_INTERVAL=60*60*24*5
                  -DBONUS_PIXELS=0
                  -DMATRIX_WIDTH=100
                  -DMATRIX_HEIGHT=1

                  -DLED_PIN0=14
                  ${dev_esp32_c6.build_flags}
