#!/bin/sh

set -e

if [ ! -c $PLATFORMIO_UPLOAD_PORT ]
then
  export PLATFORMIO_UPLOAD_PORT=$(ioreg -l | awk -F\" '/IOCalloutDevice.*usbserial/ {P=$4}; END{print P}')
fi


E=kitch

pio run    --target upload -e $E

pio device monitor -e $E

# (stty 115200 ; cat -u) < $PLATFORMIO_UPLOAD_PORT
